name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    name: Build and Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    steps:

    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_REPO }}

    - uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test
